extends Node

signal language_changed(lang_code: String)

var current: String = "fr" :
	set(val):
		current = val
		GameConfig.set_meta("lang", val)  # persiste entre scènes
		language_changed.emit(val)

const STRINGS = {
	"fr": {
		"subtitle":       "Stratégie & Conquête  •  Totally Spies",
		"play":           "JOUER",
		"quit":           "Quitter",
		"back":           "← Retour",
		"footer":         "Projet 2PROJ — SUPINFO Paris",
		"lang_title":     "Langue / Language / Idioma",
		"mode_title":     "Mode de jeu",
		"mode_2p":        "2 Joueurs",
		"mode_2p_desc":   "Deux joueurs humains sur le même écran",
		"mode_1p":        "1 Joueur  (vs IA)",
		"mode_1p_desc":   "Jouez contre une intelligence artificielle",
		"diff_title":     "Difficulté de l'IA",
		"diff_easy":      "Facile",
		"diff_easy_desc": "L'IA attaque rarement et recrute peu",
		"diff_med":       "Moyen",
		"diff_med_desc":  "L'IA gère ses troupes et sait attaquer",
		"diff_hard":      "Difficile",
		"diff_hard_desc": "L'IA est agressive et optimise ses revenus",
		"map_title":      "Choisissez une carte",
		"player_turn":    "%s — Tour %d",
		"gold":           "Or : %d",
		"income":         "+%d /tour",
		"camps":          "Camps : %d",
		"unit_label":     "Unité : %s",
		"queue_empty":    "vide",
		"queue_type":     "Type",
		"queue_label":    "File",
		"victory_title":  "VICTOIRE !",
		"victory_sub":    "a remporté la conquête !",
		"victory_turns":  "Partie terminée en %d tours",
		"replay":         "REJOUER",
		"player1":        "Joueur 1",
		"player2":        "Joueur 2",
		"squad_title":    "Choisissez votre équipe",
		"squad_p1":       "Joueur 1 — Choisissez votre équipe",
		"squad_p2":       "Joueur 2 — Choisissez votre équipe",
		"turn_title":     "C'est votre tour !",
		"turn_number":    "Tour %d",
		"turn_prompt":    "Cliquez n'importe où pour commencer",
		"msg_select":     "%s — Sélectionnez un de vos camps",
		"msg_selected":   "%s sélectionné — Cliquez une cible ou recrutez",
		"msg_not_yours":  "Ce camp ne vous appartient pas !",
		"msg_move":       "%d unités déplacées vers %s",
		"msg_attack":     "Attaque sur %s !",
		"msg_need_move":  "Il faut au moins 2 unités pour se déplacer !",
		"msg_need_atk":   "Il faut au moins 2 unités pour attaquer !",
		"msg_produced":   "Unité produite à %s",
		"msg_no_camp":    "Sélectionnez d'abord un camp !",
		"msg_no_gold":    "Pas assez d'or ! (10 or requis)",
		"msg_no_gold_p":  "Pas assez d'or ! (%d or requis)",
		"msg_queue_full": "File pleine ! (3 unités maximum en attente)",
		"msg_recruited":  "%s ajouté à la file de %s",
		"multiplayer":    "Multijoueur",
		"leaderboard":    "Classement",
		"settings":       "Paramètres",
		"new_game":       "NOUVELLE PARTIE",
		"mode_1p_short":  "vs IA",
		"player_names":   "Noms des joueurs",
		"next_map":       "Suivant : Choisir la map",
		"play_btn":       "Jouer",
		"player_col":     "Joueur",
		"wins":           "Victoires",
		"losses":         "Défaites",
		"volume":         "Volume",
		"msg_victory":    "VICTOIRE DE %s !",
		"ai_vs_you":      "AI VS TOI",
	},
	"en": {
		"subtitle":       "Strategy & Conquest  •  Totally Spies",
		"play":           "PLAY",
		"quit":           "Quit",
		"back":           "← Back",
		"footer":         "Project 2PROJ — SUPINFO Paris",
		"lang_title":     "Langue / Language / Idioma",
		"mode_title":     "Game Mode",
		"mode_2p":        "2 Players",
		"mode_2p_desc":   "Two human players on the same screen",
		"mode_1p":        "1 Player  (vs AI)",
		"mode_1p_desc":   "Play against an artificial intelligence",
		"diff_title":     "AI Difficulty",
		"diff_easy":      "Easy",
		"diff_easy_desc": "The AI rarely attacks and recruits few units",
		"diff_med":       "Medium",
		"diff_med_desc":  "The AI manages its troops and knows how to attack",
		"diff_hard":      "Hard",
		"diff_hard_desc": "The AI is aggressive and optimizes its income",
		"map_title":      "Choose a map",
		"player_turn":    "%s — Turn %d",
		"gold":           "Gold: %d",
		"income":         "+%d /turn",
		"camps":          "Camps: %d",
		"end_turn":       "End Turn",
		"unit_label":     "Unit: %s",
		"queue_empty":    "empty",
		"queue_type":     "Type",
		"queue_label":    "Queue",
		"victory_title":  "VICTORY!",
		"victory_sub":    "has won the conquest!",
		"victory_turns":  "Game over in %d turns",
		"replay":         "REPLAY",
		"player1":        "Player 1",
		"player2":        "Player 2",
		"squad_title":    "Choose your squad",
		"squad_p1":       "Player 1 — Choose your squad",
		"squad_p2":       "Player 2 — Choose your squad",
		"turn_title":     "It's your turn!",
		"turn_number":    "Turn %d",
		"turn_prompt":    "Click anywhere to start",
		"msg_select":     "%s — Select one of your camps",
		"msg_selected":   "%s selected — Click a target or recruit",
		"msg_not_yours":  "This camp doesn't belong to you!",
		"msg_move":       "%d units moved to %s",
		"msg_attack":     "Attack on %s!",
		"msg_need_move":  "Need at least 2 units to move!",
		"msg_need_atk":   "Need at least 2 units to attack!",
		"msg_produced":   "Unit produced at %s",
		"msg_no_camp":    "Select a camp first!",
		"msg_no_gold":    "Not enough gold! (10 gold required)",
		"msg_no_gold_p":  "Not enough gold! (%d gold required)",
		"msg_queue_full": "Queue full! (3 units max waiting)",
		"msg_recruited":  "%s added to %s queue",
		"multiplayer":    "Multiplayer",
		"leaderboard":    "Leaderboard",
		"settings":       "Settings",
		"new_game":       "NEW GAME",
		"mode_1p_short":  "vs AI",
		"player_names":   "Player names",
		"next_map":       "Next: Choose map",
		"play_btn":       "Play",
		"player_col":     "Player",
		"wins":           "Wins",
		"losses":         "Losses",
		"volume":         "Volume",
		"msg_victory":    "%s WINS!",
		"ai_vs_you":      "AI VS YOU",
	},
	"es": {
		"subtitle":       "Estrategia & Conquista  •  Totally Spies",
		"play":           "JUGAR",
		"quit":           "Salir",
		"back":           "← Volver",
		"footer":         "Proyecto 2PROJ — SUPINFO París",
		"lang_title":     "Langue / Language / Idioma",
		"mode_title":     "Modo de juego",
		"mode_2p":        "2 Jugadores",
		"mode_2p_desc":   "Dos jugadores humanos en la misma pantalla",
		"mode_1p":        "1 Jugador  (vs IA)",
		"mode_1p_desc":   "Juega contra una inteligencia artificial",
		"diff_title":     "Dificultad de la IA",
		"diff_easy":      "Fácil",
		"diff_easy_desc": "La IA raramente ataca y recluta poco",
		"diff_med":       "Medio",
		"diff_med_desc":  "La IA gestiona sus tropas y sabe atacar",
		"diff_hard":      "Difícil",
		"diff_hard_desc": "La IA es agresiva y optimiza sus ingresos",
		"map_title":      "Elige un mapa",
		"player_turn":    "%s — Turno %d",
		"gold":           "Oro: %d",
		"income":         "+%d /turno",
		"camps":          "Camp.: %d",
		"end_turn":       "Fin de turno",
		"unit_label":     "Unidad: %s",
		"queue_empty":    "vacío",
		"queue_type":     "Tipo",
		"queue_label":    "Cola",
		"victory_title":  "¡VICTORIA!",
		"victory_sub":    "¡ha ganado la conquista!",
		"victory_turns":  "Partida terminada en %d turnos",
		"replay":         "REPETIR",
		"player1":        "Jugador 1",
		"player2":        "Jugador 2",
		"squad_title":    "Elige tu equipo",
		"squad_p1":       "Jugador 1 — Elige tu equipo",
		"squad_p2":       "Jugador 2 — Elige tu equipo",
		"turn_title":     "¡Es tu turno!",
		"turn_number":    "Turno %d",
		"turn_prompt":    "Haz clic en cualquier lugar para comenzar",
		"msg_select":     "%s — Selecciona uno de tus campamentos",
		"msg_selected":   "%s seleccionado — Haz clic en un objetivo o recluta",
		"msg_not_yours":  "¡Este campamento no te pertenece!",
		"msg_move":       "%d unidades movidas a %s",
		"msg_attack":     "¡Ataque a %s!",
		"msg_need_move":  "¡Necesitas al menos 2 unidades para moverte!",
		"msg_need_atk":   "¡Necesitas al menos 2 unidades para atacar!",
		"msg_produced":   "Unidad producida en %s",
		"msg_no_camp":    "¡Selecciona primero un campamento!",
		"msg_no_gold":    "¡Oro insuficiente! (10 oro requerido)",
		"msg_no_gold_p":  "¡Oro insuficiente! (%d oro requerido)",
		"msg_queue_full": "¡Cola llena! (máximo 3 unidades)",
		"msg_recruited":  "%s añadido a la cola de %s",
		"multiplayer":    "Multijugador",
		"leaderboard":    "Clasificación",
		"settings":       "Configuración",
		"new_game":       "NUEVA PARTIDA",
		"mode_1p_short":  "vs IA",
		"player_names":   "Nombres de jugadores",
		"next_map":       "Siguiente: Elegir mapa",
		"play_btn":       "Jugar",
		"player_col":     "Jugador",
		"wins":           "Victorias",
		"losses":         "Derrotas",
		"volume":         "Volumen",
		"msg_victory":    "¡%s GANA!",
		"ai_vs_you":      "IA VS TÚ",
	}
}


func _ready() -> void:
	# Restaure la langue sauvegardée dans GameConfig (persiste entre scènes)
	if GameConfig.has_meta("lang"):
		current = GameConfig.get_meta("lang")


func t(key: String) -> String:
	var lang_dict : Dictionary = STRINGS.get(current, STRINGS["fr"])
	return lang_dict.get(key, key)
