extends Node

signal language_changed(lang_code: String)

var current: String = "fr" :
	set(val):
		current = val
		GameConfig.set_meta("lang", val)  # persiste entre scènes
		language_changed.emit(val)

const STRINGS = {
	"fr": {
		"subtitle":       "Stratégie & Conquête  •  Totally Spies",
		"play":           "JOUER",
		"quit":           "Quitter",
		"back":           "← Retour",
		"footer":         "Projet 2PROJ — SUPINFO Paris",
		"lang_title":     "Langue / Language / Idioma",
		"mode_title":     "Mode de jeu",
		"mode_2p":        "2 Joueurs",
		"mode_2p_desc":   "Deux joueurs humains sur le même écran",
		"mode_1p":        "1 Joueur  (vs IA)",
		"mode_1p_desc":   "Jouez contre une intelligence artificielle",
		"diff_title":     "Difficulté de l'IA",
		"diff_easy":      "Facile",
		"diff_easy_desc": "L'IA attaque rarement et recrute peu",
		"diff_med":       "Moyen",
		"diff_med_desc":  "L'IA gère ses troupes et sait attaquer",
		"diff_hard":      "Difficile",
		"diff_hard_desc": "L'IA est agressive et optimise ses revenus",
		"map_title":      "Choisissez une carte",
		"player_turn":    "%s — Tour %d",
		"gold":           "Or : %d",
		"income":         "+%d /tour",
		"camps":          "Camps : %d",
		"unit_label":     "Unité : %s",
		"queue_empty":    "vide",
		"queue_type":     "Type",
		"queue_label":    "File",
		"victory_title":  "VICTOIRE !",
		"victory_sub":    "a remporté la conquête !",
		"replay":         "REJOUER",
		"player1":        "Joueur 1",
		"player2":        "Joueur 2",
		"squad_title":    "Choisissez votre équipe",
		"squad_p1":       "Joueur 1 — Choisissez votre équipe",
		"squad_p2":       "Joueur 2 — Choisissez votre équipe",
		"turn_title":     "C'est votre tour !",
		"turn_number":    "Tour %d",
		"turn_prompt":    "Cliquez n'importe où pour commencer",
		"msg_select":     "%s — Sélectionnez un de vos camps",
		"msg_selected":   "%s sélectionné — Cliquez une cible ou recrutez",
		"msg_not_yours":  "Ce camp ne vous appartient pas !",
		"msg_move":       "%d unités déplacées vers %s",
		"msg_attack":     "Attaque sur %s !",
		"msg_need_move":  "Il faut au moins 2 unités pour se déplacer !",
		"msg_need_atk":   "Il faut au moins 2 unités pour attaquer !",
		"msg_produced":   "Unité produite à %s",
		"msg_no_camp":    "Sélectionnez d'abord un camp !",
		"msg_no_gold":    "Pas assez d'or ! (10 or requis)",
		"msg_no_gold_p":  "Pas assez d'or ! (%d or requis)",
		"msg_queue_full": "File pleine ! (3 unités maximum en attente)",
		"msg_recruited":  "%s ajouté à la file de %s",
		"multiplayer":    "Multijoueur",
		"leaderboard":    "Classement",
		"settings":       "Paramètres",
		"new_game":       "NOUVELLE PARTIE",
		"mode_1p_short":  "vs IA",
		"player_names":   "Noms des joueurs",
		"next_map":       "Suivant : Choisir la map",
		"play_btn":       "Jouer",
		"player_col":     "Joueur",
		"wins":           "Victoires",
		"losses":         "Défaites",
		"volume":         "Volume",
		"msg_victory":    "VICTOIRE DE %s !",
		"ai_vs_you":      "AI VS TOI",
		# Play screen
		"main_menu":      "Menu Principal",
		# Descriptions maps
		"map1_desc":      "Urbain · Rivière · Pont",
		"map2_desc":      "Forêt dense · Hauts revenus",
		"map3_desc":      "Île · Océan · Ports",
		# Pause menu
		"pause_title":    "— PAUSE —",
		"pause_sub":      "W.O.O.H.P · Mission en attente",
		"pause_resume":   "▶  Reprendre",
		"pause_options":  "⚙  Options",
		"pause_menu":     "↺  Menu principal",
		"pause_quit":     "✕  Quitter le jeu",
		"pause_hint":     "ESC — reprendre",
		"opt_title":      "⚙  OPTIONS",
		"opt_language":   "Langue :",
		"opt_sound":      "Volume Son :",
		"opt_music":      "Volume Musique :",
		"opt_display":    "Affichage :",
		"opt_close":      "✕  Fermer",
		"ai_desc":        "Affronte une IA · Choisis ton équipe et la difficulté",
		"ai_launch":      "→  LANCER",
		"mp_desc":        "Joue en ligne · Crée ou rejoins une mission",
		"mp_launch":      "→  EN MISSION",
		# AI screen
		"your_team":      "Ton équipe : ",
		"ai_level_label": "Niveau de l'IA :",
		# HUD
		"players_title":  "— Joueurs —",
		"eliminated":     "éliminé",
		"units_selected": "✦  %d unité(s) sélectionnée(s)",
		"stat_melee":     "mêlée",
		"queue_empty_lbl":"file vide",
		# Victory / Defeat
		"won_victory":       "%s a remporté la victoire",
		"territory_lost":    "Votre territoire a été perdu",
		"agent_secured":     "L'agent a sécurisé tous les territoires",
		"mission_complete":  "MISSION  ACCOMPLIE",
		"mission_failed":    "MISSION  ÉCHOUÉE",
		"victory_scr_title": "✦  VICTOIRE  ✦",
		"defeat_scr_title":  "✖  DÉFAITE  ✖",
		"play_again":        "↺  Rejouer",
		"try_again":         "↺  Réessayer",
		"quit_btn":          "✕  Quitter",
		"stat_duration":     "⏱  Durée",
		"stat_camps_peak":   "🏠  Camps max",
		"stat_camps_final":  "🏁  Camps finaux",
		"stat_income_peak":  "💰  Revenu max",
		"stat_units_lost":   "💀  Unités perdues",
		"stat_winner":       "🏆  Vainqueur",
		# Recap IA
		"recap_title":      "✦  RÉCAP MISSION  ✦",
		"recap_mode":       "Mode",
		"recap_vs_ai":      "VS Intelligence Artificielle",
		"recap_diff":       "Difficulté",
		"recap_map":        "Carte",
		"recap_launch":     "→  LANCER LA MISSION",
		"diff_easy_label":  "Recrue (Facile)",
		"diff_med_label":   "Agente (Moyen)",
		"diff_hard_label":  "Super Agente (Difficile)",
		# Login
		"login_badge":      "W.O.O.H.P · CONNEXION",
		"login_title":      "✦  CONNEXION AGENT  ✦",
		"login_username":   "Nom d'agent",
		"login_password":   "Code secret",
		"login_btn":        "→  ENTRER EN MISSION",
		"login_register":   "Créer un compte agent",
		# Salle d'attente
		"lobby_title":      "✦  SALLE D'ATTENTE  ✦",
		"lobby_team_a":     "✦ Équipe A",
		"lobby_team_b":     "✦ Équipe B",
		"lobby_launch":     "→  LANCER LA MISSION",
		"lobby_quit":       "← Quitter la mission",
		# Multi screen
		"multi_title":      "MISSION EN LIGNE",
		"your_agent":       "Ton agent : ",
		"multi_create":     "✦  CRÉER UNE MISSION",
		"multi_create_desc":"Héberge une partie — les autres agents pourront te rejoindre",
		"multi_join":       "⟳  REJOINDRE UNE MISSION",
		"multi_join_desc":  "Parcours les missions disponibles et rejoins une partie",
		# Format screen
		"format_title":     "✦  FORMAT DE MISSION  ✦",
		"format_1v1":       "✦  1 VS 1  —  Duel d'agentes",
		"format_1v1_desc":  "Face à face — la mission la plus intense",
		"format_2v2":       "✦  2 VS 2  —  Équipes de choc",
		"format_2v2_desc":  "Coordonne-toi avec ton équipière",
		"format_3v3":       "✦  3 VS 3  —  Guerre totale",
		"format_3v3_desc":  "Le plus grand affrontement W.O.O.H.P",
		# Choix map online
		"choixmap_title":   "✦  CHOISIR LA MAP  ✦",
		"omap1_desc":       "Île luxueuse avec boutiques",
		"omap2_desc":       "Bases tech dans la jungle",
		"omap3_desc":       "Archipel avec ports navals",
		# Nom room
		"nomroom_title":    "✦  NOM DE LA MISSION  ✦",
		"nomroom_label":    "Nom de la room",
		"nomroom_launch":   "→  LANCER LA MISSION",
		# Liste rooms
		"listrooms_title":   "✦  REJOINDRE UNE MISSION  ✦",
		"listrooms_refresh": "⟳  Actualiser",
		"listrooms_loading": "Chargement des missions…",
		"listrooms_empty":   "Aucune mission disponible",
		"listrooms_count":   "%d mission(s) disponible(s)",
		"listrooms_players": "joueurs",
		"listrooms_full":    "PLEINE",
		# Salle d'attente — statuts
		"lobby_all_ready":   "Tout le monde est là !",
		"lobby_waiting":     "En attente… %d/%d",
		"lobby_waiting_host":"En attente du lancement… %d/%d",
	},
	"en": {
		"subtitle":       "Strategy & Conquest  •  Totally Spies",
		"play":           "PLAY",
		"quit":           "Quit",
		"back":           "← Back",
		"footer":         "Project 2PROJ — SUPINFO Paris",
		"lang_title":     "Langue / Language / Idioma",
		"mode_title":     "Game Mode",
		"mode_2p":        "2 Players",
		"mode_2p_desc":   "Two human players on the same screen",
		"mode_1p":        "1 Player  (vs AI)",
		"mode_1p_desc":   "Play against an artificial intelligence",
		"diff_title":     "AI Difficulty",
		"diff_easy":      "Easy",
		"diff_easy_desc": "The AI rarely attacks and recruits few units",
		"diff_med":       "Medium",
		"diff_med_desc":  "The AI manages its troops and knows how to attack",
		"diff_hard":      "Hard",
		"diff_hard_desc": "The AI is aggressive and optimizes its income",
		"map_title":      "Choose a map",
		"player_turn":    "%s — Turn %d",
		"gold":           "Gold: %d",
		"income":         "+%d /turn",
		"camps":          "Camps: %d",
		"end_turn":       "End Turn",
		"unit_label":     "Unit: %s",
		"queue_empty":    "empty",
		"queue_type":     "Type",
		"queue_label":    "Queue",
		"victory_title":  "VICTORY!",
		"victory_sub":    "has won the conquest!",
		"replay":         "REPLAY",
		"player1":        "Player 1",
		"player2":        "Player 2",
		"squad_title":    "Choose your squad",
		"squad_p1":       "Player 1 — Choose your squad",
		"squad_p2":       "Player 2 — Choose your squad",
		"turn_title":     "It's your turn!",
		"turn_number":    "Turn %d",
		"turn_prompt":    "Click anywhere to start",
		"msg_select":     "%s — Select one of your camps",
		"msg_selected":   "%s selected — Click a target or recruit",
		"msg_not_yours":  "This camp doesn't belong to you!",
		"msg_move":       "%d units moved to %s",
		"msg_attack":     "Attack on %s!",
		"msg_need_move":  "Need at least 2 units to move!",
		"msg_need_atk":   "Need at least 2 units to attack!",
		"msg_produced":   "Unit produced at %s",
		"msg_no_camp":    "Select a camp first!",
		"msg_no_gold":    "Not enough gold! (10 gold required)",
		"msg_no_gold_p":  "Not enough gold! (%d gold required)",
		"msg_queue_full": "Queue full! (3 units max waiting)",
		"msg_recruited":  "%s added to %s queue",
		"multiplayer":    "Multiplayer",
		"leaderboard":    "Leaderboard",
		"settings":       "Settings",
		"new_game":       "NEW GAME",
		"mode_1p_short":  "vs AI",
		"player_names":   "Player names",
		"next_map":       "Next: Choose map",
		"play_btn":       "Play",
		"player_col":     "Player",
		"wins":           "Wins",
		"losses":         "Losses",
		"volume":         "Volume",
		"msg_victory":    "%s WINS!",
		"ai_vs_you":      "AI VS YOU",
		# Play screen
		"main_menu":      "Main Menu",
		# Map descriptions
		"map1_desc":      "Urban · River · Bridge",
		"map2_desc":      "Dense forest · High income",
		"map3_desc":      "Island · Ocean · Ports",
		# Pause menu
		"pause_title":    "— PAUSE —",
		"pause_sub":      "W.O.O.H.P · Mission on hold",
		"pause_resume":   "▶  Resume",
		"pause_options":  "⚙  Options",
		"pause_menu":     "↺  Main Menu",
		"pause_quit":     "✕  Quit Game",
		"pause_hint":     "ESC — resume",
		"opt_title":      "⚙  OPTIONS",
		"opt_language":   "Language:",
		"opt_sound":      "Sound Volume:",
		"opt_music":      "Music Volume:",
		"opt_display":    "Display:",
		"opt_close":      "✕  Close",
		"ai_desc":        "Play vs AI · Choose your squad and difficulty",
		"ai_launch":      "→  LAUNCH",
		"mp_desc":        "Play online · Create or join a mission",
		"mp_launch":      "→  ON MISSION",
		# AI screen
		"your_team":      "Your team: ",
		"ai_level_label": "AI Level:",
		# HUD
		"players_title":  "— Players —",
		"eliminated":     "eliminated",
		"units_selected": "✦  %d unit(s) selected",
		"stat_melee":     "melee",
		"queue_empty_lbl":"empty queue",
		# Victory / Defeat
		"won_victory":       "%s has won the victory",
		"territory_lost":    "Your territory has been lost",
		"agent_secured":     "Agent has secured all territories",
		"mission_complete":  "MISSION  COMPLETE",
		"mission_failed":    "MISSION  FAILED",
		"victory_scr_title": "✦  VICTORY  ✦",
		"defeat_scr_title":  "✖  DEFEAT  ✖",
		"play_again":        "↺  Play Again",
		"try_again":         "↺  Try Again",
		"quit_btn":          "✕  Quit",
		"stat_duration":     "⏱  Duration",
		"stat_camps_peak":   "🏠  Peak camps",
		"stat_camps_final":  "🏁  Final camps",
		"stat_income_peak":  "💰  Peak income",
		"stat_units_lost":   "💀  Units lost",
		"stat_winner":       "🏆  Winner",
		# Recap IA
		"recap_title":      "✦  MISSION RECAP  ✦",
		"recap_mode":       "Mode",
		"recap_vs_ai":      "VS Artificial Intelligence",
		"recap_diff":       "Difficulty",
		"recap_map":        "Map",
		"recap_launch":     "→  LAUNCH MISSION",
		"diff_easy_label":  "Recruit (Easy)",
		"diff_med_label":   "Agent (Medium)",
		"diff_hard_label":  "Super Agent (Hard)",
		# Login
		"login_badge":      "W.O.O.H.P · CONNECTION",
		"login_title":      "✦  AGENT LOGIN  ✦",
		"login_username":   "Agent name",
		"login_password":   "Secret code",
		"login_btn":        "→  ENTER MISSION",
		"login_register":   "Create agent account",
		# Salle d'attente
		"lobby_title":      "✦  WAITING ROOM  ✦",
		"lobby_team_a":     "✦ Team A",
		"lobby_team_b":     "✦ Team B",
		"lobby_launch":     "→  LAUNCH MISSION",
		"lobby_quit":       "← Leave mission",
		# Multi screen
		"multi_title":      "ONLINE MISSION",
		"your_agent":       "Your agent: ",
		"multi_create":     "✦  CREATE A MISSION",
		"multi_create_desc":"Host a game — other agents can join you",
		"multi_join":       "⟳  JOIN A MISSION",
		"multi_join_desc":  "Browse available missions and join a game",
		# Format screen
		"format_title":     "✦  MISSION FORMAT  ✦",
		"format_1v1":       "✦  1 VS 1  —  Agent Duel",
		"format_1v1_desc":  "Face to face — the most intense mission",
		"format_2v2":       "✦  2 VS 2  —  Strike Teams",
		"format_2v2_desc":  "Coordinate with your teammate",
		"format_3v3":       "✦  3 VS 3  —  Total War",
		"format_3v3_desc":  "The greatest W.O.O.H.P confrontation",
		# Online map selection
		"choixmap_title":   "✦  CHOOSE MAP  ✦",
		"omap1_desc":       "Luxury island with shops",
		"omap2_desc":       "Tech bases in the jungle",
		"omap3_desc":       "Archipelago with naval ports",
		# Room name
		"nomroom_title":    "✦  MISSION NAME  ✦",
		"nomroom_label":    "Room name",
		"nomroom_launch":   "→  LAUNCH MISSION",
		# Room list
		"listrooms_title":   "✦  JOIN A MISSION  ✦",
		"listrooms_refresh": "⟳  Refresh",
		"listrooms_loading": "Loading missions…",
		"listrooms_empty":   "No missions available",
		"listrooms_count":   "%d mission(s) available",
		"listrooms_players": "players",
		"listrooms_full":    "FULL",
		# Lobby status
		"lobby_all_ready":   "Everyone is here!",
		"lobby_waiting":     "Waiting… %d/%d",
		"lobby_waiting_host":"Waiting for launch… %d/%d",
	},
	"es": {
		"subtitle":       "Estrategia & Conquista  •  Totally Spies",
		"play":           "JUGAR",
		"quit":           "Salir",
		"back":           "← Volver",
		"footer":         "Proyecto 2PROJ — SUPINFO París",
		"lang_title":     "Langue / Language / Idioma",
		"mode_title":     "Modo de juego",
		"mode_2p":        "2 Jugadores",
		"mode_2p_desc":   "Dos jugadores humanos en la misma pantalla",
		"mode_1p":        "1 Jugador  (vs IA)",
		"mode_1p_desc":   "Juega contra una inteligencia artificial",
		"diff_title":     "Dificultad de la IA",
		"diff_easy":      "Fácil",
		"diff_easy_desc": "La IA raramente ataca y recluta poco",
		"diff_med":       "Medio",
		"diff_med_desc":  "La IA gestiona sus tropas y sabe atacar",
		"diff_hard":      "Difícil",
		"diff_hard_desc": "La IA es agresiva y optimiza sus ingresos",
		"map_title":      "Elige un mapa",
		"player_turn":    "%s — Turno %d",
		"gold":           "Oro: %d",
		"income":         "+%d /turno",
		"camps":          "Camp.: %d",
		"end_turn":       "Fin de turno",
		"unit_label":     "Unidad: %s",
		"queue_empty":    "vacío",
		"queue_type":     "Tipo",
		"queue_label":    "Cola",
		"victory_title":  "¡VICTORIA!",
		"victory_sub":    "¡ha ganado la conquista!",
		"replay":         "REPETIR",
		"player1":        "Jugador 1",
		"player2":        "Jugador 2",
		"squad_title":    "Elige tu equipo",
		"squad_p1":       "Jugador 1 — Elige tu equipo",
		"squad_p2":       "Jugador 2 — Elige tu equipo",
		"turn_title":     "¡Es tu turno!",
		"turn_number":    "Turno %d",
		"turn_prompt":    "Haz clic en cualquier lugar para comenzar",
		"msg_select":     "%s — Selecciona uno de tus campamentos",
		"msg_selected":   "%s seleccionado — Haz clic en un objetivo o recluta",
		"msg_not_yours":  "¡Este campamento no te pertenece!",
		"msg_move":       "%d unidades movidas a %s",
		"msg_attack":     "¡Ataque a %s!",
		"msg_need_move":  "¡Necesitas al menos 2 unidades para moverte!",
		"msg_need_atk":   "¡Necesitas al menos 2 unidades para atacar!",
		"msg_produced":   "Unidad producida en %s",
		"msg_no_camp":    "¡Selecciona primero un campamento!",
		"msg_no_gold":    "¡Oro insuficiente! (10 oro requerido)",
		"msg_no_gold_p":  "¡Oro insuficiente! (%d oro requerido)",
		"msg_queue_full": "¡Cola llena! (máximo 3 unidades)",
		"msg_recruited":  "%s añadido a la cola de %s",
		"multiplayer":    "Multijugador",
		"leaderboard":    "Clasificación",
		"settings":       "Configuración",
		"new_game":       "NUEVA PARTIDA",
		"mode_1p_short":  "vs IA",
		"player_names":   "Nombres de jugadores",
		"next_map":       "Siguiente: Elegir mapa",
		"play_btn":       "Jugar",
		"player_col":     "Jugador",
		"wins":           "Victorias",
		"losses":         "Derrotas",
		"volume":         "Volumen",
		"msg_victory":    "¡%s GANA!",
		"ai_vs_you":      "IA VS TÚ",
		# Play screen
		"main_menu":      "Menú Principal",
		# Descripciones mapas
		"map1_desc":      "Urbano · Río · Puente",
		"map2_desc":      "Bosque denso · Altos ingresos",
		"map3_desc":      "Isla · Océano · Puertos",
		# Pause menu
		"pause_title":    "— PAUSA —",
		"pause_sub":      "W.O.O.H.P · Misión en espera",
		"pause_resume":   "▶  Reanudar",
		"pause_options":  "⚙  Opciones",
		"pause_menu":     "↺  Menú principal",
		"pause_quit":     "✕  Salir del juego",
		"pause_hint":     "ESC — reanudar",
		"opt_title":      "⚙  OPCIONES",
		"opt_language":   "Idioma:",
		"opt_sound":      "Volumen Sonido:",
		"opt_music":      "Volumen Música:",
		"opt_display":    "Pantalla:",
		"opt_close":      "✕  Cerrar",
		"ai_desc":        "Juega vs IA · Elige tu equipo y dificultad",
		"ai_launch":      "→  LANZAR",
		"mp_desc":        "Juega en línea · Crea o únete a una misión",
		"mp_launch":      "→  EN MISIÓN",
		# AI screen
		"your_team":      "Tu equipo: ",
		"ai_level_label": "Nivel de IA:",
		# HUD
		"players_title":  "— Jugadores —",
		"eliminated":     "eliminado",
		"units_selected": "✦  %d unidad(es) seleccionada(s)",
		"stat_melee":     "cuerpo a cuerpo",
		"queue_empty_lbl":"cola vacía",
		# Victory / Defeat
		"won_victory":       "%s ha ganado la victoria",
		"territory_lost":    "Tu territorio ha sido perdido",
		"agent_secured":     "El agente ha asegurado todos los territorios",
		"mission_complete":  "MISIÓN  COMPLETADA",
		"mission_failed":    "MISIÓN  FALLIDA",
		"victory_scr_title": "✦  VICTORIA  ✦",
		"defeat_scr_title":  "✖  DERROTA  ✖",
		"play_again":        "↺  Jugar de nuevo",
		"try_again":         "↺  Intentar de nuevo",
		"quit_btn":          "✕  Salir",
		"stat_duration":     "⏱  Duración",
		"stat_camps_peak":   "🏠  Campamentos máx.",
		"stat_camps_final":  "🏁  Campamentos finales",
		"stat_income_peak":  "💰  Ingresos máx.",
		"stat_units_lost":   "💀  Unidades perdidas",
		"stat_winner":       "🏆  Ganador",
		# Recap IA
		"recap_title":      "✦  RESUMEN MISIÓN  ✦",
		"recap_mode":       "Modo",
		"recap_vs_ai":      "VS Inteligencia Artificial",
		"recap_diff":       "Dificultad",
		"recap_map":        "Mapa",
		"recap_launch":     "→  LANZAR MISIÓN",
		"diff_easy_label":  "Recluta (Fácil)",
		"diff_med_label":   "Agente (Medio)",
		"diff_hard_label":  "Super Agente (Difícil)",
		# Login
		"login_badge":      "W.O.O.H.P · CONEXIÓN",
		"login_title":      "✦  LOGIN AGENTE  ✦",
		"login_username":   "Nombre de agente",
		"login_password":   "Código secreto",
		"login_btn":        "→  ENTRAR EN MISIÓN",
		"login_register":   "Crear cuenta de agente",
		# Salle d'attente
		"lobby_title":      "✦  SALA DE ESPERA  ✦",
		"lobby_team_a":     "✦ Equipo A",
		"lobby_team_b":     "✦ Equipo B",
		"lobby_launch":     "→  LANZAR MISIÓN",
		"lobby_quit":       "← Abandonar misión",
		# Multi screen
		"multi_title":      "MISIÓN EN LÍNEA",
		"your_agent":       "Tu agente: ",
		"multi_create":     "✦  CREAR UNA MISIÓN",
		"multi_create_desc":"Aloja una partida — otros agentes podrán unirse",
		"multi_join":       "⟳  UNIRSE A UNA MISIÓN",
		"multi_join_desc":  "Explora las misiones disponibles y únete",
		# Format screen
		"format_title":     "✦  FORMATO DE MISIÓN  ✦",
		"format_1v1":       "✦  1 VS 1  —  Duelo de agentes",
		"format_1v1_desc":  "Cara a cara — la misión más intensa",
		"format_2v2":       "✦  2 VS 2  —  Equipos de choque",
		"format_2v2_desc":  "Coordínate con tu compañera",
		"format_3v3":       "✦  3 VS 3  —  Guerra total",
		"format_3v3_desc":  "El mayor enfrentamiento W.O.O.H.P",
		# Selección mapa online
		"choixmap_title":   "✦  ELEGIR MAPA  ✦",
		"omap1_desc":       "Isla de lujo con tiendas",
		"omap2_desc":       "Bases tech en la jungla",
		"omap3_desc":       "Archipiélago con puertos navales",
		# Nombre de room
		"nomroom_title":    "✦  NOMBRE DE MISIÓN  ✦",
		"nomroom_label":    "Nombre de la sala",
		"nomroom_launch":   "→  LANZAR MISIÓN",
		# Lista de salas
		"listrooms_title":   "✦  UNIRSE A UNA MISIÓN  ✦",
		"listrooms_refresh": "⟳  Actualizar",
		"listrooms_loading": "Cargando misiones…",
		"listrooms_empty":   "Sin misiones disponibles",
		"listrooms_count":   "%d misión/misiones disponible(s)",
		"listrooms_players": "jugadores",
		"listrooms_full":    "LLENA",
		# Estado sala de espera
		"lobby_all_ready":   "¡Todo el mundo está aquí!",
		"lobby_waiting":     "Esperando… %d/%d",
		"lobby_waiting_host":"Esperando lanzamiento… %d/%d",
	}
}


func _ready() -> void:
	# Restaure la langue sauvegardée dans GameConfig (persiste entre scènes)
	if GameConfig.has_meta("lang"):
		current = GameConfig.get_meta("lang")


func t(key: String) -> String:
	var lang_dict : Dictionary = STRINGS.get(current, STRINGS["fr"])
	return lang_dict.get(key, key)
